trigger: none 
  
pool:
  vmImage: ubuntu-latest

parameters:
- name: globallyUniqueName
  displayName: Enter a globally unique name
  type: string
  default: structurizr
    
variables:
  subscription: 'subscription'
  resourceGroup: 'rg-${{parameters.globallyUniqueName}}'
  storageAccountName: 'sa${{lower(parameters.globallyUniqueName)}}'
  appServiceName: 'web${{parameters.globallyUniqueName}}'

steps:
  - checkout: self

  - task: AzurePowerShell@5
    displayName: 'Deploy resources'
    inputs:
      azureSubscription: ${{variables.subscription}}
      scriptType: FilePath
      scriptPath: $(build.sourcesDirectory)/deploy.ps1
      scriptArguments: 
        -resourceGroup ${{variables.resourceGroup}} `
        -storageAccountName ${{variables.storageAccountName}} `
        -appServiceName ${{variables.appServiceName}}
      azurePowerShellVersion: latestVersion
      pwsh: true